name: python_test

on:
  push:
    branches:
      - main
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.0'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      #- name: Install dependencies
       # run: pip install -r requirements.txt # replace with the command to install your Python dependencies
      - name: Run Python script
        run: python .github/example.py  # replace with the path to your Python script
      
